### ISSUE TITLE
Update images for positive emotion condition

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/factorial-design-breathing-study#22] opened 2024-06-26 22:27 UTC
Per the [6/26 Slack thread](https://matheremotion.slack.com/archives/C06RTKC864W/p1719256509000449), please update images for positive emotion condition.  Updated images have been added here:

https://drive.google.com/drive/folders/1tbf5GG-6u6VO8FLDfUvuv5vVFf2gttZE

**Comment by noah10** [comment] 2024-06-27 17:09
This is done in v1.0.3.

**Comment by choipaul92** [comment] 2024-06-27 22:28
I still have to scroll down to press "continue" but the pictures are no longer huge

- Green Leaves: Instructions are update
- Five stones on water: Instructions are updated

**Comment by choipaul92** [comment] 2024-07-02 19:04
After the 1.0.5 update, the picture's size are good. I still do have to scroll down to press "continue" 

Note: I cannot close this issue because I am not the author of this issue.

**Comment by cho890** [comment] 2024-07-02 19:08
@noah10 Any way to eliminate scrolling down to hit 'continue' for the positive emotion image screens, the way you did for the breathing instructions screen?

**Comment by noah10** [comment] 2024-07-11 16:31
Unfortunately I don't think I'm going to be able to fix this without access to one of the machines that exhibits the problem. I tried setting up my machine at the same resolution and tried using an external monitor set to that resolution, but neither of them showed the problem. Just guessing at a fix, building it, and then asking someone for screenshots will take forever to iterate on. I'm going to close this for now but we can re-open it if I get a machine I can reproduce this on.

**Closed by noah10** 2024-07-11 16:31 UTC
