### ISSUE TITLE
Bonus Rewards are not added up correctly

### ISSUE THREAD

**Issue by shaakhini** [EmotionCognitionLab/factorial-design-breathing-study#24] opened 2024-06-26 23:43 UTC
![Screenshot 2024-06-26 163917](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/172333455/740cb723-17b9-4d36-9547-d8692c6cd833)

I earned 4 dollars for my first session of the day and 3 dollars for the second one, but the app says I earned 9 dollars total for the day instead of 7. It is also only giving 6 dollars for the two sessions instead of 8.

**Comment by noah10** [comment] 2024-06-27 01:55
Closing as duplicate of #23.

**Closed by noah10** 2024-06-27 01:55 UTC
